# Generated by Django 5.2.4 on 2025-07-17 09:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_userdetails_userroleallocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRoleAllocation',
            new_name='UserDetails',
        ),
    ]
